<a target="_blank" href="https://colab.research.google.com/github/ares2012/MDL/blob/master/NumPy.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
# ● 예제1
# 넘파이 & 파이썬 비교: 파이썬 리스트의 단점
# 여러 가지 다른 타입을 담을 수 있도록 만들어졌기 때문에 상대적으로 느릴 수 밖에 없다.
# 넘파이는 이런 단점을 극복하기 위해서 다른 타입은 담을 수 없고, 동일한 타입에 대해서만 저장하여 속도를 빠르게 개선
# 즉, 숫자면 숫자로, 문자면 문자로 하나의 동일한 타입으로 통일
# 속도 뿐만 아니라 메모리 사용 등에 있어서도 매우 효율적
# 배열간의 산술 연산 등을 수행하는 게 가능
# 따라서, 수치 계산에 매우 빠르고 대용량 데이터분석, 다차원배열 연산 가능(ndarray, N-dimentsional)

import numpy as np

a = [ 1, 2, 3, 4, 5 ]
b = [ 6, 7, 8, 9, 10 ]

print( type(a) ) # <class 'list'>
print( type(b) ) # <class 'list'>
print( a + b )

a1 = np.array( a )
b1 = np.array( b )
print( type(a1) ) # <class 'numpy.ndarray'>
print( type(b1) )
print( a1 + b1 )
print( a1 - b1 )
print( a1 * b1 )
print( a1 / b1 )

# 메서드 사용
print( np.add(a1, b1) )
print( np.subtract(a1, b1) )
print( np.multiply(a1, b1) )

<class 'list'>
<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [2]:
# ● 예제2
# 넘파이 데이터 타입
'''
i - integer (정수)
b - boolean (참거짓)
u - unsigned integer (부호없는 정수)
f - float (소수)
c - complex (복소수)
O - object (객체)
S - string (문자열)
'''

import numpy as np
ar = np.array( [1, 2, 3, 4, 5] )
print( type(ar[0]) ) # <class 'numpy.int64'>
print( type(ar[0]) )
print( ar.size )
print( ar[ar.size-1] )
print( ar[len(ar)-1] )

<class 'numpy.int64'>
<class 'numpy.int64'>
5
5
5


In [3]:
# ● 예제3
import numpy as np

# array
a = np.array( [1, 2, 3, 4, 5] )
print( type(a) )
print( a )
print( type(a[0]) )

print( "---------------------------------------- 1" )
# [1] : 메서드인지? 아닌지? 헷갈려요..ㅠ.ㅠ

print( "---------------------------------------- 2" )
# [2] : dtype 사용해서 배열 요소의 데이터타입 확인하기
b = np.array( [1, 2, 3, 4, 5] )
print( b.dtype )
print( type(b) )

print( "---------------------------------------- 3" )
# [3] : 배열 요소가 정수형인데 하나가 실수형으로 되어 있으면 이때 dtype 출력 결과는?
c = np.array( [1, 2, 3., 4, 5] )
print( c.dtype )
print( type(c) )

print( "---------------------------------------- 4" )
# [4] : dtype 사용해서 배열 요소 타입 변경하기1
d = np.array( [1, 2, 3, 4, 5], dtype=float )
print( d.dtype )
print( d )

print( "---------------------------------------- 5" )
# [5] : dtype 사용해서 배열 요소 타입 변경하기2
e = np.array( [1, 2, 3, 4, 5], dtype='float64' )
print( e.dtype )
print( e )

print( "---------------------------------------- 6" )
#  numpy.str_ 배열 요소 데이터타입을 numpy.int64 데이터타입으로 변경하시오?
b = [ '100', '200', '300' ]
print( type(b) )

b1 = np.array( b )
print( type(b1) )
print( type(b1[0]) )

b2 = np.array( b, dtype=int )
print( type(b2) )
print( type(b2[0]) )

<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.int64'>
---------------------------------------- 1
---------------------------------------- 2
int64
<class 'numpy.ndarray'>
---------------------------------------- 3
float64
<class 'numpy.ndarray'>
---------------------------------------- 4
float64
[1. 2. 3. 4. 5.]
---------------------------------------- 5
float64
[1. 2. 3. 4. 5.]
---------------------------------------- 6
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.str_'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [4]:
# ● 예제4
# 배열과 숫자 연산 ( 배열간의 연산도 가능 )
import numpy as np

data5 = [ 1, 2, 3, 4, 5 ]
e = 3

# 배열 연산
# print( data5 + e )

# 배열로 변경 후 연산 수행
data5_ar = np.array( data5 )

print( data5_ar + e )
print( data5_ar - e )
print( data5_ar * e )
print( data5_ar / e )
print( data5_ar % e )
print( data5_ar // e )

[4 5 6 7 8]
[-2 -1  0  1  2]
[ 3  6  9 12 15]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[1 2 0 1 2]
[0 0 1 1 1]


In [5]:
# ● 예제5
# 다차원 배열 만들기
import numpy as np

data5 = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float )
print( data5 )
print( data5.dtype )
print( data5[2, 1] )
print( type(data5) )
print( data5.shape )
print( data5.ndim )

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64
8.0
<class 'numpy.ndarray'>
(3, 3)
2


In [6]:
# ● 예제6
import numpy as np

data6 = [ '1', '2', '3' ]

data6_ar = np.array( data6, dtype='i8' )
print( data6_ar.dtype )
print( data6_ar[data6_ar.size-1] )
print( type(data6_ar[data6_ar.size-1]) )

# 범위 체크하기 - int64
info_int64 = np.iinfo( np.int64 )
print( type(info_int64) )
print( info_int64 )
print( info_int64.max )
print( info_int64.min )
print( type(info_int64.max) )
print( info_int64.bits )

int64
3
<class 'numpy.int64'>
<class 'numpy.iinfo'>
Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

9223372036854775807
-9223372036854775808
<class 'int'>
64


In [7]:
# ● 예제7
import numpy as np

data7 = np.array( [1, 2, 3] )
print( data7 ) # [1 2 3]
print( data7.dtype )

data7_f = data7.astype( np.float64 )
print( data7_f ) # [1. 2. 3.]
print( data7_f.dtype )

# 데이터타입 변경 시 주의!
import numpy as np

# [1] 여러 가지 방식
d7 = np.array( [1, 2, 3], dtype='f8')
print( d7.dtype )
print( d7 )

# [2] 넘파이 배열로 변경 후 데이터타입 변경 --> astype()
d7 = d7.astype( np.int64 )
print( d7.dtype )
print( d7 )

[1 2 3]
int64
[1. 2. 3.]
float64
float64
[1. 2. 3.]
int64
[1 2 3]


In [8]:
# ● 예제8
import numpy as np

# arange()
data8 = np.arange(1, 20, 2)
print( data8 )
print( type(data8) )
print( data8.dtype )
print( type(data8[data8.size-1]) )

data8_1 = np.arange(1, 10)
print( data8_1 )

data8_2 = np.arange(10)
print( data8_2 )
print( "--------------------------------------------------------" )

# arange() + reshape() : 체이닝
dataRe = np.arange(1, 10).reshape(3, 3)
print( dataRe )
print()

dataRe_1 = np.arange(1, 13).reshape(3, 4)
print( dataRe_1 )
print()

dataRe_1 = dataRe_1.reshape(2, 6)
print( dataRe_1 )
print( "--------------------------------------------------------" )

# reshape(3, 3, 3)
dataRe_2 = np.arange(1, 28).reshape(3, 3, 3)
print( dataRe_2 )

[ 1  3  5  7  9 11 13 15 17 19]
<class 'numpy.ndarray'>
int64
<class 'numpy.int64'>
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
--------------------------------------------------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [1]:
# ● 예제9
import numpy as np

# 1차원 배열 생성
data9 = np.array( [1, 2, 3, 4, 5] )
print( data9.shape )
print( data9.ndim )

# 인덱스 접근
print( data9[4] )
print( data9[data9.size-1] )

# 요소 수정
data9[data9.size-1] = 500
print( data9[data9.size-1] ) # 500

# 1차원 배열 생성 - arange()
print( "------------------------------------------ arange()" )
data9_1 = np.arange(10)
print( data9_1 )
print( data9_1.shape )

# 1차원 배열 생성 - zero()
print( "------------------------------------------ zeros()" )
data9_2 = np.zeros(7)
print( data9_2 )
print( data9_2.shape )
print( data9_2.dtype )

# 1차원 배열 생성 - ones()
print( "------------------------------------------ ones()" )
data9_3 = np.ones(6)
print( data9_3 )
print( data9_3.shape )
print( data9_3.dtype )

(5,)
1
5
5
500
------------------------------------------ arange()
[0 1 2 3 4 5 6 7 8 9]
(10,)
------------------------------------------ zeros()
[0. 0. 0. 0. 0. 0. 0.]
(7,)
float64
------------------------------------------ ones()
[1. 1. 1. 1. 1. 1.]
(6,)
float64


In [2]:
# ● 예제10
# 2차원 배열의 형태
import numpy as np

# 2차원 배열 생성
data10 = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]] )
print( data10 )
print( data10.shape )
print( data10.ndim )
print( "data10[0, 0] => ", data10[0, 0] ) # 1
print( "data10[1, 1] => ", data10[1, 1] ) # 5
print( "data10[2, 2] => ", data10[2, 2] ) # 9

# 2차원 배열 생성 - arange()
print( "------------------------------------------ arange()" )
data10_1 = np.arange(1, 17).reshape(4, 4)
print( data10_1 )
print( data10_1.shape )
print( data10_1.ndim )

# 8x2 모양으로 변경
data10_1 = data10_1.reshape(8, 2)
print( data10_1 )

# zeros() 사용 시 2차원 형태로 배열 만들기
print( "------------------------------------------ zeros()" )
data10_2 = np.zeros((3, 3))
print( data10_2 )
print( data10_2.shape )
print( data10_2.dtype )

# ones() 사용 시 2차원 형태로 배열 만들기
print( "------------------------------------------ ones()" )
data10_3 = np.ones((4, 2))
print( data10_3 )
print( data10_3.shape )
print( data10_3.dtype )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
data10[0, 0] =>  1
data10[1, 1] =>  5
data10[2, 2] =>  9
------------------------------------------ arange()
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
------------------------------------------ zeros()
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
float64
------------------------------------------ ones()
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
(4, 2)
float64


In [3]:
# ● 예제11
# 3차원 배열의 형태

# 3차원 배열 생성
data11 = np.array(
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [1, 2],
            [3, 4]
        ],
        [
            [1, 2],
            [3, 4]
        ]
    ]
)
print( data11 )
print( data11.shape ) # (3, 2, 2)

# 3차원 배열 생성 - arange()
print( "------------------------------------------ arange()" )
data11_1 = np.arange(1, 28).reshape(3, 3, 3)
print( data11_1 )
print( data11_1.shape ) # (3, 3, 3)
print( data11_1.ndim ) # 3

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
(3, 2, 2)
------------------------------------------ arange()
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
3


In [4]:
# ● 예제12
import numpy as np

# full() : 사용자 값으로 배열 만들기
data12 = np.full( (3, 3), 3.14 )
print( data12 )
print( data12.shape ) # (3, 3)
print( data12.dtype ) # float64
print()

# eye() : 단위행렬(주대각선의 요소가 모두 1이고, 나머지는 모두 0인 행렬)
data12_eye = np.eye(3)
print( data12_eye )
print()

# tri() : 삼각행렬(삼각형 모양의 배열)
data12_tri = np.tri(3)
print( data12_tri )
print()

# empty() : 초기화되지 않은 배열 생성(기존 메모리 위치에 존재하는 어떤 값이 올 수 있음)
data12_empty = np.empty(5)
print( data12_empty )
print()

temp = np.empty( (3, 2), dtype=float )
print( temp )

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
(3, 3)
float64

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]

[1. 1. 1. 1. 1.]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
# ● 예제13
# ~와 비슷한 배열
import numpy as np

data13 = np.arange(1, 13).reshape(2, 6)
print( data13 )
print()

# np.zeros_like()
# np.ones_like()
# np.full_like()
# np.empty_like()

data13_like_zeros = np.zeros_like( data13 )
print( data13_like_zeros )
print()

data13_like_ones = np.ones_like( data13 )
print( data13_like_ones )


# 넘파이로 다양한 배열 형태 만들기 (복습 + New)
import numpy as np

# ● 1차원 배열 만들기 --> zeros(), ones(), full()
data_zeros = np.zeros( 10, dtype=int )
data_ones = np.ones( 10, dtype=int )
data_full = np.full( (4,), 1, dtype=float )


# ● 2차원 배열 만들기
# full()
data2 = np.full( (3, 3), 1 )
print( data2 )

# zeros()
data2_z = np.zeros( (3, 4), dtype=int )
print( data2_z )
print()

# ones()
data2_o = np.ones( (4, 4), dtype=int )
print( data2_o )


# ● 3차원 배열 만들기
# full()
data3 = np.full( (3, 3, 3), 10 )
print( data3 )

print( "------------------------------------------------- 1" )
data3 = np.arange(2 * 3 * 4).reshape((2, 3, 4))
print( data3 )
print( data3[-1, -1, -1] )

print( "------------------------------------------------- 2" )
data3_2 = np.arange(1, 2 * 3 * 4 + 1).reshape((2, 3, 4))
print( data3_2 )

print( "------------------------------------------------- 3" )
data3_3 = np.arange(1, (2 * 3 * 4) * 2, 2).reshape((2, 3, 4))
print( data3_3 )

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]]
------------------------------------------------- 1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
23
------------------------------------------------- 2
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
------------------------------------------------- 3
[[[ 1  3  5  7]
  [ 9 11 13 15]
  [17 19 21 23]]

 [[25 27 29 31]
  [33 35 37 39]
  [41 43 45 47]]]


In [6]:
# ● 예제14
import numpy as np

# random()
data14 = np.random.random( (2, 4) )
print( data14 )
print( data14.dtype ) # float64
print()

# randint()
data14_randint = np.random.randint( 1, 10, (4, 4) )
print( data14_randint )
print()

print( np.random.randint(2, size=5) )
print( np.random.randint(2, 9, size=5) )
print( np.random.randint(1, 10, size=(2, 3)) )

[[0.88139754 0.35893869 0.32276133 0.95798958]
 [0.71288707 0.54954102 0.56256389 0.84256786]]
float64

[[6 3 9 6]
 [8 5 7 6]
 [5 7 1 6]
 [9 4 1 1]]

[0 0 0 0 1]
[6 2 3 7 8]
[[2 1 1]
 [9 9 4]]


In [7]:
# ● 예제15
# shape, ndim, dtype, size, itemsize, nbytes, strides
# stride: 배열의 각 차원에서 다음 요소로 이동하기 위한 메모리 상의 바이트 수
import numpy as np

# 1차원 배열에서 strides 값 체크
data1 = np.arange( 7 )
print( data1 )
print( data1.dtype )
print( data1.itemsize )
print( data1.nbytes )
print( data1.strides )

data2 = np.arange(7, dtype='int32')
print( data2 )
print( data2.dtype )
print( data2.itemsize )
print( data2.nbytes )
print( data2.strides )

# 2차원 배열에서 strides 값 체크
data3 = np.arange( 1, 10 ).reshape( 3, 3 )
print( data3 )
print( data3.dtype )
print( data3.itemsize )
print( data3.nbytes )
print( data3.strides )

# 3차원 배열에서 strides 값 체크
data4 = np.arange( 24 ).reshape( 3, 2, 4 )
print( data4 )
print( data4.dtype )
print( data4.itemsize )
print( data4.nbytes )
print( data4.strides )

[0 1 2 3 4 5 6]
int64
8
56
(8,)
[0 1 2 3 4 5 6]
int32
4
28
(4,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
8
72
(24, 8)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
int64
8
192
(64, 32, 8)
